### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 6: ordinal not in range(128)

### ISSUE THREAD

**Issue by busla** [scrapy/loginform#8]
I get this error when running `python -m loginform -u myusername -p mypassword https://armenningar.felog.is/UsersLogin.aspx` 

```
url: https://armenningar.felog.is/UsersLogin.aspx
method: POST
payload:
- __VIEWSTATE: ZNDD7u5s1fSp3w0n0GJ90WQUHDDPrxriAQ8+zk0GjcbyUmz/1zkwW+6yC/R1hLWYHXAC41a+6b9vxtdYAPhaZypXhbWLPDGCHDzJjdSSej4RnaOGDsUODpeadYNhRF7PAXdMW05l+/eAEaGRsfJViDWKeMi1IOOEqjMbumIE5y59vxI0P+4elY61LK/W1PfM6adno7Ks3FJVYP1D1sThwPQCJs8ngbHVl2FkkC4Qs24Ci1SLUzNw9sC1J8xCU9oawRdhidR5iLmJx4IIzIH+D7HjZrS2bcHY8Lo1bzeY8GKhKx0pDJOu233u1QBBslJgNLCvcH8rQbhLLEk6ZJdkDOBIg3stHxIQT3BNhG24dv4xPkSpDvxzzIEYQxnQCmYPsSWr7ZBmq4AI5Y4+mprApAmRAU0nGk5YN67SHJAQoi9CIA/jarhWB7YM/CpcjQt52iBsbYMzz02zOBFl040D6By2PJSCKN7R+eUaUYBEouj39dFtiWo+C20dzg9BSdsii7FYpDfUPDBAiMUZfrPsIS02dyguxMfwVmI+3YnVNz6XUu+dgcqegBE6c7DQsaP3TKKMT81FDQbBt3AOy8pmpCK4KlB5M0Bi+be1UfyyCy+uty//wZ4pr7lCZ7Shyj8fFqyzKGJ/9zAwBa1fo3NRge9QEBo=
- __VIEWSTATEENCRYPTED: 
- __EVENTVALIDATION: QhZVGQrl99DLoBzHMjoJ+BlHDknr/D8N11RYWQvoLWV+EIBnYlr/Bs2TtzuCpOol5aAn5/M4mE0DstB3OEffO5c+7YB/DqIMT15WQqADdcOAJ3waUAq+rMXFGidE54HUeM8RfA==
- ctl00$ContentPlaceHolder1$textUsername: myusername
- ctl00$ContentPlaceHolder1$textPassword: mypassword
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/nonni/Code/norix/norix/loginform/loginform.py", line 102, in <module>
    sys.exit(main())
  File "/Users/nonni/Code/norix/norix/loginform/loginform.py", line 98, in main
    print '- {0}: {1}'.format(k, v)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 6: ordinal not in range(128)
```

Changing line 99 in loginform.py to `print(k + ': ' + v)` solves the error.

**Comment by dangra** [comment]
thx!
